name: CI
on: [push]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        julia_version: ["1"]
    name: julia ${{ matrix.julia_version }}
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia_version }}
      - uses: julia-actions/julia-runtest@latest
        env:
          JULIA_DEPOT_PATH: ~/.julia-${{ runner.name }}
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./lcov.info
          flags: unittests
          name: codecov-umbrella
